import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Header from '../components/Header'
import fs from "fs/promises"
import styles from "../styles/Home.module.css"
import Comic from '../components/Comic'
import Footer from '../components/Footer'

export default function Home({ latestComics }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header
				isOpenIndex={true}
			/>
			<main style={{
				width: '100%',
				display: 'grid',
				placeItems: 'center',
			}}>
				<h3
				className={styles.title}
				>Lastest Comics</h3>
				<div
					className={styles.latestComicsContainer}
				>
					{latestComics.map((comic) => {
						return (
							<Comic
								comic={comic}
							/>
						)
					})}
				</div>
			</main>
			<Footer/>
		</>
	)
}

export async function getStaticProps() {
	const files = await fs.readdir("./comics")
	const lastestComicsFiles = files.slice(-8, files.length)
	const prmisesReadFiles = lastestComicsFiles.map(async (file) => {
		const content = await fs.readFile(`./comics/${file}`, "utf-8")
		return JSON.parse(content)
	})

	const latestComics = await Promise.all(prmisesReadFiles)
	return {
		props: {
			latestComics
		},
	}
}
