import Head from 'next/head'
import Link from 'next/link'
import Image from 'next/image'
import Header from '../components/Header'
import fs from "fs/promises"
import styles from "../styles/Home.module.css"

export default function Home({ latestComics }) {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Header />
			<main style={{
				width: '100%',
				display: 'grid',
				placeItems: 'center',
			}}>
				<h3
				className={styles.title}
				>Lastest Comics</h3>
				<div
					className={styles.latestComicsContainer}
				>
					{latestComics.map((comic) => {
						return (
							<Link
								href={`/comics/${comic.id}`}
								key={comic.id}
								className={styles.latestComic}
								>
								<h4
									style={{
										color: "#000",
										fontSize: "15px",
									}}
								>{comic.title}</h4>
								<Image width="400" height="500" src={comic.img} alt={comic.alt} style={{
									objectFit: "contain",
								}}/>
							</Link>
						)
					})}
				</div>
			</main>
		</>
	)
}

export async function getStaticProps(context) {
	const files = await fs.readdir("./comics")
	const lastestComicsFiles = files.slice(-8, files.length)
	const prmisesReadFiles = lastestComicsFiles.map(async (file) => {
		const content = await fs.readFile(`./comics/${file}`, "utf-8")
		return JSON.parse(content)
	})

	const latestComics = await Promise.all(prmisesReadFiles)
	return {
		props: {
			latestComics
		},
	}
}
